Improve error reporting

diff --git a/gnome-screenshot-wrapper b/gnome-screenshot-wrapper
--- a/gnome-screenshot-wrapper
+++ b/gnome-screenshot-wrapper
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # Copyright (c) 2016-2017  Erik Martin-Dorel
-# Version: 0.9.3-git
+# Version: 0.9.3
 
 function is_among() {
     local arg="$1"
@@ -31,6 +31,7 @@ function main() {
     prefix="$(xdg-user-dir PICTURES)/"
     local format='%Y-%m-%d_%H-%M-%S'
     local suffix='_Screenshot.png'
+    local template="$lockdir/tmp.XXXXXXXXXX.png"
 
     local interactFlags=("-c" "--clipboard" "-i" "--interactive" "--gapplication-service" "-h" "--help" "--help-all" "--help-gtk" "--help-gapplication")
     # --gapplication-service is triggered when clicking on the .desktop icon
@@ -45,7 +46,11 @@ function main() {
 
     if [ "$interact" = "false" ]; then
         get_lock
-        tmp=$(mktemp "$lockdir/tmp.XXXXXXXXXX.png")
+        tmp=$(mktemp "$template") || ret="$?"
+        if [ "$ret" -ne 0 ]; then
+            echo "$prog: failed to create '$template'." >&2
+            exit "$ret"
+        fi
 
         /usr/bin/gnome-screenshot -f "$tmp" "$@" || ret="$?"
         if [ "$ret" -ne 0 ]; then
